project:
  type: book
  output-dir: _book

book:
  title: "Identificaci칩n de los Focos de la Transmisi칩n de las Arbovirosis & Manejo Integrado de Aedes en R"
  reader-mode: true
  page-footer:
    left: |
      Focos de Transmisi칩n de las Arbovirosis & Manejo Integrado de Aedes".
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/cover.jpg
  favicon: images/cover.jpg
  site-url: https://flourishing-jelly-b34c35.netlify.app
  repo-url: https://github.com/fdzul/dtf_ima/
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - prefacio.qmd
    - intro.qmd
    
    - part: geocodificacion.qmd
      chapters:
        - bases-sinave.qmd
        - geo.qmd
    
    - part: focos_activos.qmd
      chapters:
        - cadenas_transmision.qmd
        - cadenas_transmision_r.qmd    
 

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    author-meta: "Felipe Dzul-Manzanilla & Fabi치n Correa-Morales"
    include-in-header: "plausible.html"
    callout-appearance: simple

editor: visual

