
# Geocodificación

La geocodificación es el proceso de transformar las direcciones físicas de los domicilios a coordenadas geográficas (latitud y longitud). La geocodificación se realiza a través del servicio de [Geocoding API](https://developers.google.com/maps/documentation/geocoding/overview) de Google, con la función <span style="color:RoyalBlue">***ggmap::geocode***</span> del paquete [ggmap](https://github.com/dkahle/ggmap) & la funcion <span style="color:RoyalBlue">***denhotspots::geocoden()***</span> del paquete [denhotspots](https://fdzul.github.io/denhotspots/index.html). El proceso de geocodificación se realiza en tres fases. En la **primera fase** se sube la base de datos de los casos del SINAVE a **[RStudio](https://www.rstudio.com/)** y se extrae la información del país/estado/municipio de interés. Si la geocodificación se realiza la primera vez, el proceso es més simple que la segunda vez. Dado que la frecuencia de la geocodificación es semanal y las bases de dengue son bases de datos acumulados, se requiere extraer la base de la semana actual de los casos no geocodificados (casos nuevos, casos de la presente semana) a través de realizar la diferencia entre la semana pasada (casos acumulados geocodificados, asumiendo que se geocodificó desde el primero de enero hasta la semana pasada) y la semana actual (geocodificación por segunda vez). La idea es geocodificar solo los casos que salieron la presente semana y no volver a geocodificar todas las semanas acumuladas incluida la semana actual. Finalmente el archivo se guarda con extensión csv y con el nombre del estado y la fecha, por ejemplo dengue_aguascalientes_2025_03_11 ó dengue_edo01_2025_03_11..
 
En la **segunda fase**, el archivo csv se sube a **[RStudio](https://www.rstudio.com/)**, se crea un vector de direcciones, se realiza manipulación del vector de direcciones si se requiere (por ejemplo, se sustituye # por NUM o NUMERO), se geocodifica y se guarda en archivo temporal, une la base de coordenadas y la base del sinave, finalmente se guarda en un archivo RData.

En la **tercera fase**, cuando se geocodifica por primera vez (casos acumulados del 1 de enero al 3 marzo, el archivo resultado de la segunda fase, se sube y se guarda. Pero cuando se geocodifica la segunda ves se requiere eliminar los casos descartados y unir la base acumulada (1 enero al 3 marzo) con la base de la ultima semana (10 marzo). Acontinuación se describe el procesos para poder geocodificar en R.


# Geocodificación en R

Los requisitos básicos para realizar el proceso de geocodificación descrito en los parrafos precedentes requieren: 

   1. Contar con las siguientes APIs de Google
      a) [Geocoding API](https://developers.google.com/maps/documentation/geocoding/start?hl=es-419)
      b) [Static Maps API](https://developers.google.com/maps/documentation/maps-static?hl=es_419)
      
   La primera API sirve para geocodificar las bases del sinave y la segunda API sirve para extraer los mapas satelitales para la visualización de las cadenas de transmisión y los mapas de calor.
   
   2. Bajar la carpeta [**geocodificación_dengue_sinave**]() alojada en github y descomprimirla.
   La carpeta contiene los 32 folder para cada entidad federativa, y cada estado selecionará su carpeta correspondiente con su entidad
     

## Fase 1. Cargar base de SINAVE & extraer el estado

1. Abrir la carpeta 






