
# Introduction {.unnumbered}




<span style="color:#660033;">incluir un parrafo de focos de transmisión activa y transmisión persistente.</span>

<span style="color:#660033;">Los procedimientos y cálculos en los respectivos programas (GeoDA, ArcView, ArcGis, R y Python) es completemente restrictivo a la comunidad científica y grupos académicos con expertis. La operacionalización de los algoritmos para la identificación de los escenarios epidemiológicos u operativos en los programas de prevención y control de las arbovirosis en México, el desarrollo de paquetes y los cursos para tal fin, son los pasos siguientes que se requieren para que la estrategia de focalización y el manejo integrado de *Aedes* se escale en todo el país.</span>

<span style="color:#660033;">En el presente manual se describen los flujogramas y los pasos lógicos para la identificación de los escenarios epidemiológicos usando el análisis espacial aplicado a las bases de datos epidemiológicos y entomológicos con la finalidad de detectar los focos de transmisión persistente & los focos de transmisión activa en las área metropolitnas de México.</span>




